[pytest]
testpaths = app/tests

python_files = 
    test_auth.py
    test_documents.py

addopts = 
    -v
    --tb=short
    --strict-markers
    --cov=app
    --cov-report=term
    --cov-report=html
    --cov-fail-under=32
    --no-cov-on-fail